eureka:
  client:
    service-url:
      defaultZone: http://register-center-1:30000/eureka/,http://register-center-2:30001/eureka/
spring:
  application:
    name: entrance-guard-longconn
  main:
    allow-bean-definition-overriding: true


#hystrix的超时时间
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 30000
#ribbon的超时时间
ribbon:
  ReadTimeout: 30000
  ConnectTimeout: 30000

feign:
  client:
    config:
      remote-service:
        connectTimeout: 1000
        readTimeout: 12000


logging:
  file: ./logs/longconn.log
  file.max-size: 100MB
  pattern:
    console: "%d{yyyy/MM/dd-HH:mm:ss} [%thread] %-5level %logger- %msg%n"
    file: "%d{yyyy/MM/dd-HH:mm} [%thread] %-5level %logger- %msg%n"
  level:
    root: ERROR
    org:
      springframework:
        security: DEBUG
        web: ERROR
        hibernate: DEBUG
      apache:
        commons:
          dbcp2: DEBUG
    com:
      linktop:
        cloud:
          entranceguardlongconn:
            busi:
              CmdSocket:
                INFO


app:
  key: "9000eb71773346a789c330201bdeeb41"
longconn:
  secret: "7H;X<TkeO5pM$(jR"
  secretB64: "N0g7WDxUa2VPNXBNJChqUg=="
  host: "218.5.96.6"
  port: 9787

