server:
  port: 11000
eureka:
  client:
    service-url:
      defaultZone: http://register-center-1:30000/eureka/,http://register-center-2:30001/eureka/
spring:
  application:
    name: entrance-guard-core
  main:
    allow-bean-definition-overriding: true
  output:
    ansi:
      enabled: DETECT
  servlet:
    multipart:
      max-file-size: 4MB
      max-request-size: 20MB

  datasource:
    name: test
    url: jdbc:mysql://49.235.35.76:3306/entranceguard
    username: root
    password: 123456 # 使用druid数据源
    #type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20

#datasource config
jdbc:
  driverClassName: com.mysql.jdbc.Driver
  url: jdbc:mysql://49.235.35.76:3306/blog?zeroDateTimeBehavior=convertToNull&amp;useUnicode=true&amp;characterEncoding=utf-8
  username: root
  password: 123456

## 该配置节点为独立的节点，有很多同学容易将这个配置放在spring的节点下，导致配置无法被识别
mybatis:
#  mapper-locations: classpath:mapping/*.xml #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: com.linktop.cloud.entranceguardcore.dao # 注意：对应实体类的路径
  configuration:
    logImpl: org.apache.ibatis.logging.stdout.StdOutImpl

#文件
cbs:
    filePath:
        file:./data/cloud/

logging:
  file: ./logs/core.log
  file.max-size: 100MB
  pattern:
    console: "%d{yyyy/MM/dd-HH:mm:ss} [%thread] %-5level %logger- %msg%n"
    file: "%d{yyyy/MM/dd-HH:mm:ss} [%thread] %-5level %logger- %msg%n"
  level:
    root: ERROR
    org:
      springframework:
        security: DEBUG
        web: ERROR
        hibernate: DEBUG
      apache:
        commons:
          dbcp2: DEBUG
    com:
      linktop: INFO

app:
  key: "9000eb71773346a789c330201bdeeb41"
  rsa_private_key_pkcs8: |
            MIIEwAIBADANBgkqhkiG9w0BAQEFAASCBKowggSmAgEAAoIBAQDeuUdX0F/9f6p0
            +y+rIJBa80o6xvo793ccJRv2M30vQPWlwLgGoHUJxKi6UhGKIWZwOO6Q4bZv2FL3
            Y6lAn/xBnrnWxcqv9U1RO4b/AK81VvcAVsYlBtxG2RzxNYd/zmFjFNloxB3Y6ee1
            2a8wLzD9gcvcyHEKtrEGFkFjsP/AjCB6Uttd1TeUSbdswpFy20hPL/0feBBvb+3d
            mAgDhVfCs7nUT7E1T9y4OST7Vfy9Jf/rQjUr227prowUGcPwwT77MERDiUg0Zybc
            4Cxbhq8q08/WxfNtMOSTMtNaEkiSJAvzee4gER5/ofaGA4yboqmkBl0PJN7NoHiw
            nZhvS8jvAgMBAAECggEBAKGuUHsP2k702XHYUo9gsUpE6LLodQkJKN82lSjR0eN2
            vZxY3X56BtxTdcTkBLWIb4ux2IU2RTDGEdxi7Z/rQ70DE5c0uGGpqjn5A5OkFIyd
            F+uYEnkYlNmdjKQRns6JrCq4HOcvzxcDHeDmKIXLDD5LdglNPLpxSurHRyqud8p2
            0+/HKHXnlPao3MkT/bnOT4r8APT43uYtfJt7cD9PTsoE58re7NDO+QXcm2aLbZL9
            qRnqrR2I++ozsc9iYoYXfffTlIJf3dYZRb8rvCoClqurKAKHxa9BP/UizcUEEPST
            jSh+CR4ZqKWIhDsjuB1A5wgx+nKVpp35oKX7jESTPHkCgYEA867SCGeMVfFVzBh4
            1KzDVBA398nv87Xdxm9fUrIe5HSnh8SRGcGOUuOGORg//7hmd1LdGw/BGLhQy3/E
            PrmALWjZML4zv9tBab53sbzwl8VLolngpVu0lDQhn+PuwF/Zpv8DBhBXnMkbog4M
            kM7VjBt6JIATmS+W6b07LfqR64MCgYEA6ftA5ZMTTF9POga/1bMX2DcB5o94N62N
            mPVllOpCkGtpzHWG9voKGK44tm/ejCk63XYBnOjQ9ZItb7gUL17bq09RLqmouKzL
            S83EJcNJMCy0Uc+oBRSg4cYoQO5YZ9kSPsr1v720HydqsGusxe5iQiUg9V0SgMtA
            m5p+uUwhFSUCgYEAprvVhl6jjSKGHBIaixpyxBAc23TWtCCaUG5gAMtTi+mtv53l
            0oO3iEuZyXMoRya7JaYTF7Md4nYrAjK36lsusuNsyIc8DWhOR7ZFW931mUMrzzhE
            F6C53DYXU7m34PU0jakrPnjsGaEZQTbvrh13zFf4qQThZA1F60TJO1qZgVUCgYEA
            qAShbHm5sOz8AmoYVUd+xudxOPQrWqgI9x64rD+wPu6zEXwPx8hzeZeZ5//bKoDs
            4Vy8+cUBUGaAtCnWbNHMIm8Zl82C9+I1NiDzSj66jpp7fggE2mkewiG+hCnjV+c7
            v9WUtPRvpLN0XG1lqthsvJzW1vrXr57ErTg66aquUvUCgYEA0S3aVfZ8+U7VJt2K
            HmKiq55ZnXg5593gRG2Q8e70suVwdtLgCWBjbXhjiAUyQI7KGDNPV4P+nwxRx8d7
            t0i76anyaYROeRnWYQQFz2h4mVRHC9KIPPk/HXYTYDF9F06usdj8HfeVrHwJtmt+
            HOXX/PU3aPStQSfU/TINN5VvCa8=
longconn:
  secret: "7H;X<TkeO5pM$(jR"
  secretB64: "N0g7WDxUa2VPNXBNJChqUg=="
  host: "218.5.96.6"
  port: 9787

